* Berufsmaturitätsarbeit (WIP)
  Demo [[https://bma.fuerbringer.info][Link]].
** Installation
*** Umgebung
    Folgendes muss installiert sein:
    - NodeJS runtime ([[https://nodejs.org/][Link]])
*** Ausführung
**** Schritt 1 ─ Herunterladen
     Repo klonen: ~git clone --recursive https://github.com/fuerbringer/bma.git~

     Oder ausserhalb von Entwicklungszwecken als ZIP: [[https://github.com/fuerbringer/bma/archive/master.zip][Link]]
**** Schritt 2 ─ Vorbereitung
     Im Terminal in das geklonte directory navigieren und Dependencies installieren:
     ~npm install~
**** Schritt 3 ─ Ausführung
     Nun kann die Webapplikation ausgeführt werden: ~npm start~
     
     Die Seite ist lokal unter http://localhost:3000 aufrufbar.
** Entwicklung
   1. Alle Schritte aus ~Ausführung~ oben erledigen.
   2. Für das zu entwickelnde Feature / den Bugfix / etc. einen neuen Branch erstellen (~git checkout -b feature123~).
   3. Änderungen durchführen und hinzufügen mittels ~git add ...~ und ~git commit -m ...~.
   4. Änderungen zu GitHub pushen (~git push -u origin feature123~)
   5. Auf github.com ein Pull Request erstellen.
     
